import type { Schema } from "effect";

/** Discriminates the two message kinds of logical CQRS. */
export type MessageKind = "command" | "query";

/**
 * A message definition binds an intent-named tag to boundary schemas.
 *
 * - `payload` is decoded at dispatch time; it guards the *shape* of the
 *   input only — business rules stay in the domain layer.
 * - `success` types what the handler returns; `dispatch` infers its output
 *   from it.
 * - `failure` optionally types the handler's expected business failures so
 *   they surface in the dispatch error channel. The in-process bus never
 *   encodes it; it exists for typing (and future wire transports).
 */
export interface MessageDefinition<
  Kind extends MessageKind,
  Tag extends string,
  PayloadType,
  PayloadEncoded,
  SuccessType,
  SuccessEncoded,
  FailureType = never,
  FailureEncoded = never,
> {
  readonly _kind: Kind;
  readonly tag: Tag;
  readonly payload: Schema.Schema<PayloadType, PayloadEncoded>;
  readonly success: Schema.Schema<SuccessType, SuccessEncoded>;
  readonly failure: Schema.Schema<FailureType, FailureEncoded> | undefined;
}

/**
 * A command expresses intent to change state. Commands may carry an
 * idempotency key at dispatch time and pass through the idempotency store.
 */
export type CommandDefinition<
  Tag extends string,
  PayloadType,
  PayloadEncoded,
  SuccessType,
  SuccessEncoded,
  FailureType = never,
  FailureEncoded = never,
> = MessageDefinition<
  "command",
  Tag,
  PayloadType,
  PayloadEncoded,
  SuccessType,
  SuccessEncoded,
  FailureType,
  FailureEncoded
>;

/**
 * A query reads state and must not change it. The bus gives queries no
 * idempotency behavior — they are assumed safe to repeat.
 */
export type QueryDefinition<
  Tag extends string,
  PayloadType,
  PayloadEncoded,
  SuccessType,
  SuccessEncoded,
  FailureType = never,
  FailureEncoded = never,
> = MessageDefinition<
  "query",
  Tag,
  PayloadType,
  PayloadEncoded,
  SuccessType,
  SuccessEncoded,
  FailureType,
  FailureEncoded
>;

/**
 * Type-erased definition, used by registries and middleware that operate on
 * any message. Prefer the precise definition types in application code.
 */
export interface AnyMessageDefinition {
  readonly _kind: MessageKind;
  readonly tag: string;
  readonly payload: Schema.Schema.Any;
  readonly success: Schema.Schema.Any;
  // `Schema.Schema.Any` deliberately excludes `Schema<never>`, which is the
  // failure schema of a definition declared without one — hence the union.
  readonly failure: Schema.Schema.Any | Schema.Schema<never> | undefined;
}

/**
 * Per-dispatch envelope handed to handlers. Identity and correlation are
 * generated by the bus; `causationId` is the message that led to this one
 * (present when dispatched from inside another handled message), and
 * `actor` is the principal the action is performed for.
 */
export interface Dispatch {
  readonly messageId: string;
  readonly correlationId: string;
  readonly causationId?: string;
  readonly actor?: string;
  readonly idempotencyKey?: string;
}

interface DefineShape {
  readonly payload: Schema.Schema.Any;
  readonly success: Schema.Schema.Any;
  readonly failure?: Schema.Schema.Any;
}

const defineMessage = (kind: MessageKind, tag: string, shape: DefineShape) => ({
  _kind: kind,
  tag,
  payload: shape.payload,
  success: shape.success,
  failure: shape.failure,
});

/**
 * Declares a command with a declared failure schema. See
 * {@link MessageDefinition} for the semantics of each schema.
 */
export function defineCommand<
  const Tag extends string,
  PayloadType,
  PayloadEncoded,
  SuccessType,
  SuccessEncoded,
  FailureType,
  FailureEncoded,
>(
  tag: Tag,
  shape: {
    readonly payload: Schema.Schema<PayloadType, PayloadEncoded>;
    readonly success: Schema.Schema<SuccessType, SuccessEncoded>;
    readonly failure: Schema.Schema<FailureType, FailureEncoded>;
  },
): CommandDefinition<
  Tag,
  PayloadType,
  PayloadEncoded,
  SuccessType,
  SuccessEncoded,
  FailureType,
  FailureEncoded
>;
/** Declares a command whose handler cannot fail with a business error. */
export function defineCommand<
  const Tag extends string,
  PayloadType,
  PayloadEncoded,
  SuccessType,
  SuccessEncoded,
>(
  tag: Tag,
  shape: {
    readonly payload: Schema.Schema<PayloadType, PayloadEncoded>;
    readonly success: Schema.Schema<SuccessType, SuccessEncoded>;
  },
): CommandDefinition<Tag, PayloadType, PayloadEncoded, SuccessType, SuccessEncoded>;
export function defineCommand(tag: string, shape: DefineShape): AnyMessageDefinition {
  return defineMessage("command", tag, shape);
}

/**
 * Declares a query with a declared failure schema. See
 * {@link MessageDefinition} for the semantics of each schema.
 */
export function defineQuery<
  const Tag extends string,
  PayloadType,
  PayloadEncoded,
  SuccessType,
  SuccessEncoded,
  FailureType,
  FailureEncoded,
>(
  tag: Tag,
  shape: {
    readonly payload: Schema.Schema<PayloadType, PayloadEncoded>;
    readonly success: Schema.Schema<SuccessType, SuccessEncoded>;
    readonly failure: Schema.Schema<FailureType, FailureEncoded>;
  },
): QueryDefinition<
  Tag,
  PayloadType,
  PayloadEncoded,
  SuccessType,
  SuccessEncoded,
  FailureType,
  FailureEncoded
>;
/** Declares a query whose handler cannot fail with a business error. */
export function defineQuery<
  const Tag extends string,
  PayloadType,
  PayloadEncoded,
  SuccessType,
  SuccessEncoded,
>(
  tag: Tag,
  shape: {
    readonly payload: Schema.Schema<PayloadType, PayloadEncoded>;
    readonly success: Schema.Schema<SuccessType, SuccessEncoded>;
  },
): QueryDefinition<Tag, PayloadType, PayloadEncoded, SuccessType, SuccessEncoded>;
export function defineQuery(tag: string, shape: DefineShape): AnyMessageDefinition {
  return defineMessage("query", tag, shape);
}

/**
 * Command declaration entry point. Name commands after the intent
 * ("ApproveInvoice", not "UpdateInvoice"); the payload schema validates the
 * shape at the boundary while business rules stay in the domain.
 */
export const Command = {
  define: defineCommand,
} as const;

/**
 * Query declaration entry point. A query handler must not change state —
 * the bus assumes queries are repeatable and applies no idempotency.
 */
export const Query = {
  define: defineQuery,
} as const;
